sky:
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    host: localhost
    port: 3306
    database: sky_take_out
    username: root
    password: 123456

  alioss:
    endpoint: oss-cn-hangzhou.aliyuncs.com
    access-key-id: LTAI5t5tBiGFQjHWKHpCr46d
    access-key-secret: FG95R8eeAZQ26fgD4QmB9FPHBc7n2V
    bucket-name: ymzg-use-this

  redis:
    host: localhost
    port: 6379
    password:
    database: 0

  wechat:
    appid: wx6d88ec72288c3d0d
    secret: 2311799ab7bbf179808de8cd14de2829

spring:
  servlet:
    multipart:
      max-file-size: 10MB
      max-request-size: 20MB
